### ISSUE TITLE
[BUG] Load databases error when initial client session

### ISSUE THREAD

**Issue by gbzy** [tidb-incubator/TiBigData#218]
**Describe the bug**
Load databases when initial client session, which cause task to fail.

**What happens instead**
`Caused by: java.lang.IllegalArgumentException: invalid encoded hash data key prefix: m
	at org.tikv.shade.com.google.common.base.Preconditions.checkArgument(Preconditions.java:142) ~[pool-1-thread-7-1655696784783-flink-tidb-connector-1.13-0.0.5-SNAPSHOT.jar:?]
	at org.tikv.common.codec.MetaCodec.decodeHashDataKey(MetaCodec.java:71) ~[pool-1-thread-7-1655696784783-flink-tidb-connector-1.13-0.0.5-SNAPSHOT.jar:?]
	at org.tikv.common.codec.MetaCodec.hashGetFields(MetaCodec.java:122) ~[pool-1-thread-7-1655696784783-flink-tidb-connector-1.13-0.0.5-SNAPSHOT.jar:?]
	at org.tikv.common.catalog.CatalogTransaction.getDatabases(CatalogTransaction.java:75) ~[pool-1-thread-7-1655696784783-flink-tidb-connector-1.13-0.0.5-SNAPSHOT.jar:?]
	at org.tikv.common.catalog.Catalog$CatalogCache.loadDatabases(Catalog.java:195) ~[pool-1-thread-7-1655696784783-flink-tidb-connector-1.13-0.0.5-SNAPSHOT.jar:?]
	at org.tikv.common.catalog.Catalog$CatalogCache.<init>(Catalog.java:136) ~[pool-1-thread-7-1655696784783-flink-tidb-connector-1.13-0.0.5-SNAPSHOT.jar:?]
	at org.tikv.common.catalog.Catalog$CatalogCache.<init>(Catalog.java:124) ~[pool-1-thread-7-1655696784783-flink-tidb-connector-1.13-0.0.5-SNAPSHOT.jar:?]
	at org.tikv.common.catalog.Catalog.<init>(Catalog.java:44) ~[pool-1-thread-7-1655696784783-flink-tidb-connector-1.13-0.0.5-SNAPSHOT.jar:?]
	at org.tikv.common.TiSession.getCatalog(TiSession.java:396) ~[pool-1-thread-7-1655696784783-flink-tidb-connector-1.13-0.0.5-SNAPSHOT.jar:?]
	at io.tidb.bigdata.tidb.ClientSession.<init>(ClientSession.java:120) ~[pool-1-thread-7-1655696784783-flink-tidb-connector-1.13-0.0.5-SNAPSHOT.jar:?]
	at io.tidb.bigdata.tidb.ClientSession.create(ClientSession.java:529) ~[pool-1-thread-7-1655696784783-flink-tidb-connector-1.13-0.0.5-SNAPSHOT.jar:?]`

**Comment by xuanyu66** [comment]
Can you give more information on how to reproduce the bug
