### ISSUE TITLE
Table db.table no longer exists in TiDB

### ISSUE THREAD

**Issue by juecong** [tidb-incubator/TiBigData#249]
使用tibigdata整合flink读取数据时，程序出现
java.lang.IllegalStateException: Table `db`.`table` no longer exists in TiDB
	at io.tidb.bigdata.tidb.ClientSession.lambda$getTableMust$0(ClientSession.java:181) ~[flink-tidb-connector-1.13-0.0.5-SNAPSHOT.jar:?]
	at java.util.Optional.orElseThrow(Optional.java:290) ~[?:1.8.0_281]
	at io.tidb.bigdata.tidb.ClientSession.getTableMust(ClientSession.java:178) ~[flink-tidb-connector-1.13-0.0.5-SNAPSHOT.jar:?]
	at io.tidb.bigdata.tidb.ClientSession.getTableMust(ClientSession.java:173) ~[flink-tidb-connector-1.13-0.0.5-SNAPSHOT.jar:?]
	at io.tidb.bigdata.tidb.ClientSession.request(ClientSession.java:290) ~[flink-tidb-connector-1.13-0.0.5-SNAPSHOT.jar:?]
	at io.tidb.bigdata.tidb.RecordSetInternal.<init>(RecordSetInternal.java:61) ~[flink-tidb-connector-1.13-0.0.5-SNAPSHOT.jar:?]
	at io.tidb.bigdata.flink.connector.source.reader.TiDBSourceReader.tryMoveToNextSplit(TiDBSourceReader.java:122) ~[flink-tidb-connector-1.13-0.0.5-SNAPSHOT.jar:?]
	at io.tidb.bigdata.flink.connector.source.reader.TiDBSourceReader.pollNext(TiDBSourceReader.java:151) ~[flink-tidb-connector-1.13-0.0.5-SNAPSHOT.jar:?]
	at org.apache.flink.connector.base.source.hybrid.HybridSourceReader.pollNext(HybridSourceReader.java:85) ~[count.jar:?]
	at org.apache.flink.streaming.api.operators.SourceOperator.emitNext(SourceOperator.java:305) ~[count.jar:?]
	at org.apache.flink.streaming.runtime.io.StreamTaskSourceInput.emitNext(StreamTaskSourceInput.java:69) ~[count.jar:?]
	at org.apache.flink.streaming.runtime.io.StreamOneInputProcessor.processInput(StreamOneInputProcessor.java:66) ~[count.jar:?]
	at org.apache.flink.streaming.runtime.tasks.StreamTask.processInput(StreamTask.java:423) ~[count.jar:?]
	at org.apache.flink.streaming.runtime.tasks.mailbox.MailboxProcessor.runMailboxLoop(MailboxProcessor.java:204) ~[count.jar:?]
	at org.apache.flink.streaming.runtime.tasks.StreamTask.runMailboxLoop(StreamTask.java:684) ~[count.jar:?]
	at org.apache.flink.streaming.runtime.tasks.StreamTask.executeInvoke(StreamTask.java:639) ~[count.jar:?]
	at org.apache.flink.streaming.runtime.tasks.StreamTask.runWithCleanUpOnFail(StreamTask.java:650) ~[count.jar:?]
	at org.apache.flink.streaming.runtime.tasks.StreamTask.invoke(StreamTask.java:623) ~[count.jar:?]
	at org.apache.flink.runtime.taskmanager.Task.doRun(Task.java:779) ~[count.jar:?]
	at org.apache.flink.runtime.taskmanager.Task.run(Task.java:566) ~[count.jar:?]
	at java.lang.Thread.run(Thread.java:748) ~[?:1.8.0_281]

请问该怎样解决？

**Comment by xuanyu66** [comment]
Can you check the table, does it exit?
