### ISSUE TITLE
高版本不兼容

### ISSUE THREAD

**Issue by sunyaf** [tidb-incubator/TiBigData#262]
2023-05-13T18:14:20.780+0800	ERROR	main	io.trino.server.Server	io/trino/spi/connector/ConnectorHandleResolver
java.lang.NoClassDefFoundError: io/trino/spi/connector/ConnectorHandleResolver
	at io.tidb.bigdata.trino.ConnectorsPlugin.getConnectorFactories(ConnectorsPlugin.java:28)
	at io.trino.server.PluginManager.installPluginInternal(PluginManager.java:200)
	at io.trino.server.PluginManager.installPlugin(PluginManager.java:179)
	at io.trin

**Comment by sunxiaoguang** [comment]
Right, Trino and PrestoDB did not have a stable connector interface. Different version have to be supported individually.

**Comment by sunxiaoguang** [comment]
Contributions to support newer version are welcome.
